### ISSUE TITLE
support for legacy OS

### ISSUE THREAD

**Issue by andika207** [ShuttleBrowser/Shuttle#52]
I want to know if this browser will ever support Windows XP ?
I know that nodejs does support XP but not sure if any early version of electron is compatible with XP

**Comment by TheRolfFR** [comment]
Hello @andika207,
I have to admit your question was unexpected because we never thought to support Windows XP for Shuttle.
However, we are limited to the compatibility of ElectronJS.
And from what [I read](https://github.com/electron/electron/issues/691), support ended in 2015.

My sincere condolences from all the Shuttle team.

**Comment by andika207** [comment]
@TheRolfFR but you can use that older version of electron to compile the browser ??
or using alternative tools https://github.com/weolar/miniblink49

**Comment by TheRolfFR** [comment]
Hello @andika207,
We are not planning to support Windows XP because almost all users nowadays have a modern operating system. 
But feel free to fork the code and try adapt it by yourself.

**Comment by andika207** [comment]
@TheRolfFR however you do support W7 which is only 8 months older than XP
if I was any good on coding I would fork it myself but it's not the case.

**Comment by Vahelnir** [comment]
Windows XP was released in 2001 whereas Windows 7 was released in 2009. That's not 8 months but 8 years. 
Windows XP is in EOL. And since Windows 7 is also in EOL now, Electron will probably drop its support for it.

**Comment by andika207** [comment]
@Vahelnir Totallement faux! XP SP3 avait sorti en 2008 juste 1 an avant W7
 et à propos de la fin des msj pour XP c' était en avril 2019 et pour W7 janvier 2020 ce qui donne 8 mois. 
c'est juste un manque de volonté, même si Electron n'est plus supporté il existe des moyens alternatifs.  @boardens @TheRolfFR

**Comment by boardens** [comment]
@andika207 It is not planned to make Shuttle compatible on Windows XP on our side, considering what this implies, as @TheRolfFR pointed out. I think that, for us, the subject is closed. Feel free to do it by yourself, or not. Thank you also for keeping the same language when you open an issue.
